<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LUAstudio.Execution.Abstractions\LUAstudio.Execution.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoStudio.AvalonEdit" Version="1.0.2026.606" />
    <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
  </ItemGroup>

</Project>
